services:
  - type: web
    name: kt-project-backend
    env: node
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "24"
      - key: PORT
        value: 8000

  - type: static_site
    name: kt-project-frontend
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://kt-project-backend.onrender.com
